blank_issues_enabled: false

contact_links:
  - name: Project Discussion
    url: https://github.com/pointfreeco/swift-concurrency-extras/discussions
    about: Library Q&A, ideas, and more
  - name: Documentation
    url: https://pointfreeco.github.io/swift-concurrency-extras/main/documentation/concurrencyextras/
    about: Read the documentation
  - name: Videos
    url: https://www.pointfree.co/collections/concurrency
    about: Watch videos to get a behind-the-scenes look at how this library was motivated and built
  - name: Slack
    url: https://www.pointfree.co/slack-invite
    about: Community chat
