name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  library:
    runs-on: macos-13
    strategy:
      matrix:
        xcode: ['14.3.1']
        config: ['debug', 'release']
    steps:
      - uses: actions/checkout@v3
      - name: Select Xcode ${{ matrix.xcode }}
        run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
      - name: Run ${{ matrix.config }} tests
        run: CONFIG=${{ matrix.config }} make test

  ubuntu-tests:
    strategy:
      matrix:
        os: [ubuntu-20.04]
        config: ['debug', 'release']

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: swift build
      - name: Run tests
        run: swift test -c ${{ matrix.config }}
